// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":true,"description":"Plugin Analysis Common Base","parameters":{}},
{"name":"ExtraImage","status":true,"description":"Extra Image Display Per Scene Plugin","parameters":{"ImageList":"[]"}},
{"name":"ExtraWindow","status":true,"description":"Extra Window Display Per Scene Plugin","parameters":{"WindowList":"[]"}},
{"name":"MaterialBase","status":true,"description":"Material Base Plugin","parameters":{"ImageList":"[]","AudioList":"[]"}},
{"name":"UniqueDataLoader","status":true,"description":"Unique Data Loading Plugin","parameters":{"GlobalVariableName":"$dataUniques","UniqueDataList":"[]"}},
{"name":"OverpassTile","status":true,"description":"Overpass Plugin","parameters":{"overPathRegion":"0","overPathTerrainTag":"0","gatewayRegion":"0","gatewayTerrainTag":"0"}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"AltMenuScreen2MZ","status":false,"description":"Yet another menu screen layout","parameters":{"allowWindowDisp":"true","maxColsMenu":"4","commandRows":"2","commandCols":"4","isDisplayStatus":"true","display map name":"true","location string":"Location:","bgBitmapMenu":"","doesNotSetItemScene":"true","bgBitmapItem":"","doesNotSetSkillScene":"true","bgBitmapSkill":"","doesNotSetEquipScene":"true","bgBitmapEquip":"","doesNotSetStatusScene":"true","bgBitmapStatus":"","doesNotSetOptionScene":"true","bgBitmapOptions":"","doesNotSetSaveScene":"true","bgBitmapFile":"","doesNotSetEndScene":"true","bgBitmapGameEnd":""}},
{"name":"AltMenuScreen","status":false,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"UniqueDataLoader","status":true,"description":"Unique Data Loading Plugin","parameters":{"GlobalVariableName":"$dataUniques","UniqueDataList":"[]"}},
{"name":"ExtraWindow","status":true,"description":"Extra Window Display Per Scene Plugin","parameters":{"WindowList":"[]"}},
{"name":"wasdKeyMZ","status":true,"description":"","parameters":{}},
{"name":"PictureAnimation","status":true,"description":"ピクチャのアニメーションプラグイン","parameters":{"returnToFirstCell":"true"}},
{"name":"八方向移动 8-dir move","status":true,"description":"8-dir move","parameters":{}},
{"name":"ScreenZoom","status":true,"description":"Zoom screen whose center is specified character or player.","parameters":{}},
{"name":"SmoothTouchMove","status":true,"description":"on touch move, player can through events under the player","parameters":{}},
{"name":"QJ-Lighting","status":false,"description":"Light and Shadows [V1.0] 2022-2-13","parameters":{"lightPreset":"[]","miniLights":"[]","region":"[]","regionLights":"[]","characterShadowList":"[]","characterShadowDefault":"{\"status\":\"false\",\"tint\":\"#000000\",\"opacity\":\"1\",\"offsetX\":\"0\",\"offsetY\":\"0\",\"offsetDirX\":\"0~0~0~0\",\"offsetDirY\":\"0~0~0~0\",\"model\":\"D[]\",\"yCut\":\"0\"}","playerShadowDefault":"{\"status\":\"false\",\"tint\":\"#000000\",\"opacity\":\"1\",\"offsetX\":\"0\",\"offsetY\":\"0\",\"offsetDirX\":\"0~0~0~0\",\"offsetDirY\":\"0~0~0~0\",\"model\":\"D[]\",\"yCut\":\"0\"}","playerInitLight":"test","maskInitColor":"#292929","hidePrimordialShadow":"true","defaultOpen":"true"}},
{"name":"AlchemySystem","status":true,"description":"项目合成插件 v1.0.3","parameters":{"EnabledMenuAlchemy":"true","EnabledAlchemySwitchId":"0","EnabledGoldWindow":"true","DisplayKeyItemCategory":"false","MaxNumMakeItem":"999","MaxMaterials":"3","MakeItemSeFileName":"Heal5","MakeItemSeVolume":"90","MakeItemSePitch":"100","MakeItemSePan":"0","MenuAlchemyText":"合成","NeedMaterialText":"必要素材：","NeedPriceText":"必要経費：","TargetItemText":"生成的项目："}}
];
