// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"1200","screenHeight":"720","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"Online_Main_Core","status":true,"description":"Connect to a server with Socket.io!\r\n<Online_Main_Core>","parameters":{"Server URL":"http://localhost:8080","First Hash":"d28cb767c4272d8ab91000283c67747cb2ef7cd1"}},
{"name":"Online_Login_Core","status":true,"description":"Login window for Neldersons Online Core\r\n<Online_Login_Core>","parameters":{"Force Login on Startup":"false","socket.io connection":"true","Switch on First Shutdown":"1","Switch on Second Shutdown":"2"}},
{"name":"win10_menu","status":true,"description":"","parameters":{}},
{"name":"win10_menu_part1","status":false,"description":"菜单美化插件编写实例","parameters":{"height":"180"}}
];
